baseURL = 'https://pengguoqing.github.io/'
locale = 'en-us'
title = '匠人手记'
theme = 'PaperMod'

[params.homeInfoParams]
Title = "匠人手记"
Content = "音视频开发 / C++工程"
disableSpecial1stPost = true

[params]
ShowToc = true
TocOpen = true
ShowCodeCopyButtons: true

[params.assets]
customCSS = ["css/extended/custom.css"]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"